---
title: "re_figs_titv_BDedit"
output: html_document
---

Setup:

```{r}
library(tidyverse)
rm(list = ls())

lowers <- c(0.01, 0.1, 0.2, 0.3)
uppers <- c(0.1, 0.2, 0.3, 0.4)
etas <- c(2, 1.5, 1, 0.5)

n_iters <- 100
m <- 100
p <- 100

source('C:/Users/bdawk/Documents/KNN_project_output/R_code_and_output/code/util_funcs2.R') # assumes the working directory is the main project folder

```

Vary MAF:

```{r}
# rm(list = ls())
deltas_df <- data.frame()
source('C:/Users/bdawk/Documents/KNN_project_output/R_code_and_output/code/util_funcs2.R') # assumes the working directory is the main project folder

for (maf_idx in 1:4) {
  long.dist.vec <- NULL
  results <- matrix(nrow = n_iters, ncol = 4)
  set.seed(1989)
  
  my.eta <- 2
  
  g0 <- runif(1, min = 0.01, max = (my.eta / (my.eta + 1) - 0.01))
  g1 <- 1/(my.eta+1)
  g2 <- my.eta / (my.eta + 1) - g0
  
  PuPy.samp <- sample(
    c(3, 4, 5),
    size = p,
    prob = c(g0, g1, g2),
    replace = T
  )
  
  probs <- runif(p, lowers[maf_idx], uppers[maf_idx])
  
  for(myiter in 1:n_iters){
    # print(myiter)
    results_list <- get_means_sds(my.eta = 2, m=m, p=p, probs=probs, gammas=c(g0,g1,g2), PuPy=PuPy.samp)
    cat("Iteration: ",maf_idx,unlist(results_list[-length(results_list)]),"\n")
    results[myiter, ] <- unlist(results_list[-length(results_list)])
  }
  colnames(results) <- names(results_list)[-length(results_list)]
  results <- data.frame(results)
  
  deltas_df <-
    rbind(deltas_df, data.frame(
      Means = c(mean(results$samp.mean), mean(results$theo.mean)),
      SDs = c(mean(sqrt(results$samp.var)), mean(sqrt(results$theo.var))),
      Type = c('Simulated', 'Theoretical')
    ))
}


deltas_df$maf <- rep((lowers + uppers)/2, each = 2)
fig_9 <- deltas_df %>%
  ggplot(aes(maf, Means, 
             color = fct_reorder2(Type, maf, Means),
             fill = fct_reorder2(Type, maf, Means))) +
  geom_line() +
  geom_line(aes(y = Means - SDs), linetype = 2) +
  geom_line(aes(y = Means + SDs), linetype = 2) +
  labs(x = 'Minor allele frequency (MAF)', y = 'Distance (Mean ± SD)') +
  theme_bw() +
  theme(legend.position = c(0.8, 0.2),
        legend.title = element_blank()) +
  scale_color_viridis_d(end = 0.5) +
  scale_fill_viridis_d()
fig_9
 #########################################################################################
```


Generate varied Ti/Tv histograms
```{r}
source('C:/Users/bdawk/Documents/KNN_project_output/R_code_and_output/code/util_funcs2.R') # assumes the working 
deltas_df <- data.frame()

for (titv in 1:4) {
  my.eta <- etas[titv]
  results <- matrix(nrow = n_iters, ncol = 4)
  set.seed(1989)
  
  g0 <- runif(1, min = 0.01, max = (my.eta / (my.eta + 1) - 0.01))
  g1 <- 1/(my.eta+1)
  g2 <- my.eta / (my.eta + 1) - g0
  
  PuPy.samp <- sample(
    c(3, 4, 5),
    size = p,
    prob = c(g0, g1, g2),
    replace = T
  )
  
  probs <- runif(p, lowers[1], uppers[1])
  
  for(myiter in 1:n_iters){
    # print(myiter)
    results_list <- get_means_sds(my.eta = my.eta, m=m, p=p, probs=probs, gammas=c(g0,g1,g2), PuPy=PuPy.samp)
    results[myiter, ] <- unlist(results_list[-length(results_list)])
  }
  colnames(results) <- names(results_list)[-length(results_list)]
  results <- data.frame(results)
  
  deltas_df <-
    rbind(deltas_df, data.frame(
      Means = c(mean(results$samp.mean), mean(results$theo.mean)),
      SDs = c(mean(results$samp.var), mean(results$theo.var)),
      Type = c('Simulated', 'Theoretical')
    ))
}

```


Now let's draw:

```{r}
deltas_df$titv <- etas
deltas_df$titv <- rep(etas, each = 2)
fig_10 <- deltas_df %>%
  ggplot(aes(titv, Means, 
             color = fct_reorder2(Type, titv, Means),
             fill = fct_reorder2(Type, titv, Means))) +
  geom_line() +
  geom_line(aes(y = Means - SDs), linetype = 2) +
  geom_line(aes(y = Means + SDs), linetype = 2) +
  labs(x = 'Ti/Tv', y = 'Distance (Mean ± SD)') +
  theme_bw() +
  theme(legend.position = 'None',
        legend.title = element_blank()) +
  scale_color_viridis_d(end = 0.5) +
  scale_fill_viridis_d(end = 0.5)
fig_10

load('C:/Users/bdawk/Documents/KNN_project_output/R_code_and_output/code/titv_maf.Rdata')

cowplot::plot_grid(joy_10, fig_10, joy_9, fig_9, labels = 'AUTO',
                   align = 'h') %>%
cowplot::plot_grid(my_title, ., ncol = 1, rel_heights=c(0.07, 1)) %>%  
  ggsave(filename = 'C:/Users/bdawk/Documents/KNN_project_output/R_code_and_output/code/re_fig_5_BDedit.pdf',
       width = 7, height = 6)
```

